version: '2'

services:
  bc_db:
    container_name: bc_db
    image: postgres:9.5-alpine
    ports: [ "15432:5432" ]
    volumes: [ ".storage:/var/lib/postgresql/data" ]
    networks: [ bc-net ]
    logging:
      driver: "none"

  bc_web:
    image: bc_web:latest
    container_name: bc_web
    build: .
    command: ruby bin/start
    volumes: [ ".:/app", ".gems:/.gems" ]
    ports: [ "3001:3000" ]
    depends_on: [ bc_db ]
    links: [ bc_db ]
    networks: [ bc-net ]
    environment:
      RAILS_ENV: 'development'

volumes:
  .gems:

networks: 
  bc-net:
    driver: bridge