default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  host: bc_db
  timeout: 5000

development:
  <<: *default
  database: bluecoding-challenge_development
test:
  <<: *default
  database: bluecoding-challenge_test

production:
  <<: *default
  database: bluecoding-challenge_production