default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bluecoding-challenge_development
test: &test
  <<: *default
  database: bluecoding-challenge_test

production:
  <<: *default
  database: bluecoding-challenge_production
cucumber:
  <<: *test
